# Ignore files referenced by .gitignore (only valid at root)
gitignore: true

# Disable banner message on stdout (only valid at root)
noBanner: true

# Disable progress on stdout (only valid at root)
noProgress: true

extends: "markdownlint/style/prettier"

config:
  # Don't conflict with Prettier rules
  blanks-around-fences: false
  blanks-around-headings: false
  blanks-around-lists: false
  code-fence-style: false
  emphasis-style: false
  heading-start-left: false
  heading-style: false
  hr-style: false
  line-length: false
  list-indent: false
  list-marker-space: false
  no-blanks-blockquote: false
  no-hard-tabs: false
  no-missing-space-atx: false
  no-missing-space-closed-atx: false
  no-multiple-blanks: false
  no-multiple-space-atx: false
  no-multiple-space-blockquote: false
  no-multiple-space-closed-atx: false
  no-trailing-spaces: false
  ol-prefix: false
  strong-style: false
  ul-: false
